### ISSUE TITLE
Add search (KISS - just check format and build link)

### ISSUE THREAD

**Issue by sz-piotr** [l2beat/dydx-state-explorer#97]
Search options:
- state root hash - redirects to state update by id
- state transition fact hash - redirects to state update by id
- state update id - redirects to state update by id
- position id - redirects to position by id (problem: positions and state updates share same id space, maybe we should prefix, e.g. states are s1, s5123 and positions are p1, p5123123)
- ethereum address - redirects to position by id
- stark key - redirects to position by id
- transaction hash - redirects to forced transaction by hash
- offer id - redirects to offer id (same problem, maybe o1, o2, o123)
When nothing matches we display a 404 saying that the following search term was not found.

**Comment by krzkaczor** [comment]
How to find these things?

1. state root hash:
Example: `0x00fdf1255546cbd21f78402e14b9db04c5740b4148f15d0e8782bf0d4732c38d`
How to get it? `state_updates.root_hash` -> get id -> redirect to state-updates/id
2. ethereum address:
Example: `0x7a51D0B0Ee843c572F197c63BbB8277A957c04c5`
How to get it? `user_registration_events.eth_address` -> get stark_key -> match via `positions.public_key`
3. stark key:
Example: `0x027cda895fbaa174bf10c8e0f57561fa9aa6a93cfec32b87f1bdfe55a161e358`
How to get it? similar to eth_address
4. transaction hash - transaction hash not available yet
